### ISSUE TITLE
Have the interface timeout if Keepa is down

### ISSUE THREAD

**Issue by dehidehidehi** [akaszynski/keepa#101]
Here's a feature request/question:

Today, Keepa is down. 
This means any creation of a Keepa class instance (without necessarily calling a class method), will be left hanging for a long time before dying. 
It paused the code execution of an entire application of mine.
This made me realize it would be good to implement a timeout function which would raise an exception after a set number of seconds.

Unfortunately after some quick research, a package called "timeout-decorator" only works for Linux systems.
https://pypi.org/project/timeout-decorator/0.5.0/
It would be ideal to have a cross-platform solution.

Anybody have an idea on how we could implement this?

**Comment by chocobn69** [comment]
I think we should do that using aiohttp :
https://docs.aiohttp.org/en/stable/client_quickstart.html#timeouts

**Comment by kevincojean** [comment]
Good idea, it seems like a straightfoward implementation on the normal interface.

Keepa 1.3.0 separates the regular and async interfaces. It would seem that catching aiohttp timeouts on the async interface may be more challenging.

**Comment by akaszynski** [comment]
Sorry this took so long to get around to.  I think the easiest way to fix this is to add a class timeout parameter and pass that to `requests.get`.  I'm implementing this in #107,
