### ISSUE TITLE
 KeyError: 'NEW'

### ISSUE THREAD

**Issue by Katgitmake** [akaszynski/keepa#105]
Error is returned on occasion and not sure why? Sometimes runs smoothly - cant pinpoint issue other than server failure? Is there a fix for this? 

`price = products[i]['data']['NEW']`
KeyError: 'NEW'

**Comment by dehidehidehi** [comment]
I suspect this happens because Keepa does not have any data concerning new condition prices for this product.
A fix would be to use:
`price = products[i].get('data', dict())`

**Comment by Katgitmake** [comment]
Hmmm, solution worked, but issue can arise at any moment, even directly after a successful pull of NEW prices

**Comment by Katgitmake** [comment]
Ill close this issue, I guess for future fixes -- something to reference
