### ISSUE TITLE
unable to install on python311

### ISSUE THREAD

**Issue by Praveensenpai** [akaszynski/keepa#120]
```Successfully built keepa
Failed to build multidict yarl
ERROR: Could not build wheels for multidict, yarl, which is required to install pyproject.toml-based projects
```
Its showing this error on python 3.11 only

**Comment by akaszynski** [comment]
BTW, added testing in on https://github.com/akaszynski/keepa/pull/125 for Python 3.11. Should be good, but feel free to reopen if there's still an issue.
