### ISSUE TITLE
can we select country in keepa?

### ISSUE THREAD

**Issue by hansolGib** [akaszynski/keepa#121]
Hello, i'm using keepa 1.3.2

i put asin code from amazon japan in keepa and noticed that all information and price is in English and dollar.
so i guess keepa api is not using amazon japan, even though i selected amazon japn in keepa website.
is there any way to change country or set amazon in other countries?

**Comment by hansolGib** [comment]
oh i figured out.
just put domain="jp" in the query :D

**Comment by akaszynski** [comment]
Closing, appears resolved.
