### ISSUE TITLE
Browsing deals (api.deals) not work with deals_parms?

### ISSUE THREAD

**Issue by JohnDoe15152** [akaszynski/keepa#123]
Hello
Im new with keepa api . Since few weeks, i don't make a correct request with browsing deal (api.deals). It seems deals_params not work on request. When i put same params in keepa web page, asins are not the same with asins present on keepa webpage.
Anyone have an idea why is not correct?
Sorry for my poor english, thanks you!

**Comment by JohnDoe15152** [comment]
Here is my code:

`
import keepa
api = keepa.Keepa('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
deal_parms = {
    "page": 0,
    "domainId": 4,
    "excludeCategories": [],
    "includeCategories": [468642],
    "priceTypes": [18],
    "deltaRange": [0, 2147483647],
    "deltaPercentRange": [70, 2147483647],
    "salesRankRange": [-1,-1],
    "currentRange": [0, 2147483647],
    "minRating": -1,
    "isLowest": False,
    "isLowestOffer": False,
    "isOutOfStock": False,
    "titleSearch": "",
    "isRangeEnabled": True,
    "isFilterEnabled": False,
    "filterErotic": True,
    # "singleVariation": True,
    "hasReviews": False,
    # "isPrimeExclusive": False,
    # "mustHaveAmazonOffer": False,
    # "mustNotHaveAmazonOffer": False,
    "sortType": 1,
    "dateRange": 0,
    #"warehouseConditions": [2,3,4,5]
    "deltaLastRange": [100,500]}
products_out = api.deals(deal_parms, domain='FR')
print(products_out[:170])
`

**Comment by akaszynski** [comment]
Identified the issue and it will be fixed in #122 and included in the next release.
