### ISSUE TITLE
Spamming of wait duration

### ISSUE THREAD

**Issue by sverrirarnors** [akaszynski/keepa#132]
When `wait_for_tokens` runs, it logs the wait duration in the console. This cannot be turned off and is annoying when I save the logs of a program using keepa. Here's an example output from a script that I run frequently.

```
...
Waiting 52 seconds for additional tokens
Waiting 52 seconds for additional tokens
Waiting 56 seconds for additional tokens
Waiting 53 seconds for additional tokens
...
```

In `interface.py`, the debug level is set to `DEBUG` in line 28. It would be great to set the debug level when initializing the API so I don't have these messages polluting my logs.

**Comment by akaszynski** [comment]
Fixed in [keepa==1.3.6](https://pypi.org/project/keepa/1.3.6/).

Thanks for your work!
