### ISSUE TITLE
How to get the information of buy box used statistics

### ISSUE THREAD

**Issue by CoolDevMan** [akaszynski/keepa#148]
In fact, we are trying to obtain the figure of 17% of attached images using the API.
We have the seller's ID and the product's ASIN code.
Is that possible?
If possible, please share the sample code.
Thanks in advance.

![image](https://github.com/akaszynski/keepa/assets/54260086/6fe0b996-6f8f-4175-88fa-d5bd25f6533f)

**Comment by CoolDevMan** [comment]
Please let me know the API endpoint where I can get the information of the [Buy Box Used Statistics] section.

**Comment by akaszynski** [comment]
See #150 where I've added in an example and helper function to process the used buy box information that comes from keepa.
