### ISSUE TITLE
Changes in 1.3.7

### ISSUE THREAD

**Issue by Paul-J-Barrett** [akaszynski/keepa#154]
The changes were breaking in the new version. You used to import all of the interfaces and I was using parse_csv, keepa.parse_csv(  I am attempting to import it at the top and am testing now. Just thought I should point this out in case anyone else has issue.
```

import keepa
from keepa.interface import parse_csv
```

**Comment by Paul-J-Barrett** [comment]
That fixed it. Fyi this is about version 1.3.7

**Comment by akaszynski** [comment]
Fixed in v1.3.8
