### ISSUE TITLE
Confusing Price for specific Asin

### ISSUE THREAD

**Issue by ianrussel** [akaszynski/keepa#157]
Lets say I need to get the price for asin 'B0BD8LFL71'

       asin = 'B0BD8LFL71''
       products = api.query(asin, domain='GB')
       newprice = products[0]['data']['NEW']

       print(newprice)
        new price [  nan 35.95   nan 39.99 34.99 32.5  29.99 27.99 24.99 27.99 32.99 24.99
        22.95 19.95 37.19 24.99 37.19 37.18 32.99 37.19 37.18 37.19 32.99 37.19
        32.99 37.19 31.99 21.99 37.19 21.99 32.99 37.19 32.99 32.92 17.99 33.93
        33.94 34.14 34.34 34.37 34.14 34.02 33.6  33.57 33.53 33.46 34.02 33.99
        33.95 33.92 33.88 33.81 33.78 33.74 33.71 33.64 33.6  33.57 33.53 33.46
        33.39 33.38 33.34 34.02 33.99 33.43 33.39 33.34 33.31 33.27 33.13 33.06
       32.99 32.92 32.85 32.61 32.54 32.4  32.33 31.98 31.91 31.77 31.7  31.63
       31.56 24.99 24.3  15.   24.3  15.   24.3  15.   24.3  22.97 15.   22.97
        15.   22.97 29.35 22.97 32.91 15.   32.91 25.99 25.53 22.97 25.53 24.99]

Looking at https://www.amazon.co.uk/dp/B0BD8LFL71
The price is actually is 25.99, which is actually in the numpy array.

The question is, how/what method to extract it?

**Comment by ianrussel** [comment]
closed As I already solved it

**Comment by Haiz14** [comment]
How did u solve it?
