### ISSUE TITLE
Search products by using EAN orJAN .

### ISSUE THREAD

**Issue by chiaki1990** [akaszynski/keepa#35]
I search product price in several countries to know difference in price.
And Amazon sometimes sells same products with different ASIN .
In this case I cannot get the difference by using this API .
To resolve this problem , we can search products by using EAN or JAN too.
EAN and JAN is only code for each product . So using them is good way I think .

I asked keepa help . And I was told to do feature request .
https://keepa.com/#!discuss/t/can-we-search-by-using-ean-or-jan/7395
But I could not understand where feature request was . 
So if here was not for feature request , sorry for making trouble . 

And Thank you so much for developing this API.
I have used three APIs. This API is most simple design to use.I appreciate your works!!

**Comment by akaszynski** [comment]
Posting an issue on GitHub is the best way of requesting a feature.  I’ll be able to add this in the near future.

**Comment by akaszynski** [comment]
Added this feature in the latest release.  See the documentation at [Product Query].(https://keepaapi.readthedocs.io/en/latest/product_query.html#product-history-query)

I've also reworked the API to make it PEP8 compatible and renamed the module to ``keepa``.  Please install using:
``pip install keepa``
