### ISSUE TITLE
Sales Rank output

### ISSUE THREAD

**Issue by shashankdogra** [akaszynski/keepa#38]
Is there a way to Output the latest Sales rank for an array of ASINs
I'm new to Python, it'll really help me out if there's a hint I could use. 
I'm able to find the rank in the JSON output under the product object > csv, I'm still hopinh im looking in the right direction. Any help would be appreciated.

**Comment by akaszynski** [comment]
Please post the code you’re using so far.

**Comment by shashankdogra** [comment]
`import keepa
import logging
import inspect
logging.basicConfig()
import datetime
import requests
import numpy as np
accesskey = 'b9pms3n5aile7ihpmgvigtigf1cs2eu04ms13ikvbn92l9q559neucdidho9511f' # enter real access key here
api = keepa.Keepa(accesskey)
asins = ['B01N5ML1EA', 'B00THPUHPM', 'B01M8IKE7Y', 'B01IQCN744']
asins = np.asarray(['B01N5ML1EA', 'B00THPUHPM', 'B01M8IKE7Y', 'B01IQCN744'])
products = api.query(asins)
product = products[0]

for x in range(len(asins)):
    print asins[x]
    print ('Title is ' + products[x]['title'])
    print ('Sakes Rank ' + products[x][''])
'''
# Print ASIN and title
print('ASIN is ' + products[0]['asin'])
print('Title is ' + products[0]['title'])
'''
product['stats']`

**Comment by shashankdogra** [comment]
This is an updated code, I'm able to get a rank, I do need help in getting it for the whole array.
I've tried moving it in the For loop but still not getting it.
I'm little noobish on Python and Programming, hope I'm in right direction.
```
import keepa
import logging
import inspect
logging.basicConfig()
import datetime
import requests
import numpy as np
accesskey = 'b9pms3n5aile7ihpmgvigtigf1cs2eu04ms13ikvbn92l9q559neucdidho9511f' # enter real access key here
api = keepa.Keepa(accesskey)
asins = ['B01N5ML1EA', 'B00THPUHPM', 'B01M8IKE7Y', 'B01IQCN744']
asins = np.asarray(['B01N5ML1EA', 'B00THPUHPM', 'B01M8IKE7Y', 'B01IQCN744'])
products = api.query(asins)
product = products[0]

for x in range(len(asins)):
    print('ASIN is ' + products[x]['asin'])
    print ('Title is ' + products[x]['title'])
key = 'SALES'
history = product['data']
#print key
print history[key][-1]
```

**Comment by akaszynski** [comment]
Append this to your script to get the sales rank array ``sales`` and the times array ``sales_dt``.

```python

# sales rank array (and time) can be obtained with:
sales_dt = history['%s_time' % key]
sales = history[key]

# plot
import matplotlib.pyplot as plt
plt.step(sales_dt, sales, where='pre')
plt.show()
```

Also, I edited your post and removed the key so that no one could use your key and saturate it.

**Comment by maplejia** [comment]
hi, I purchased keepa API and have key too. I want to get historical daily sales rank per asin. for example, I want to get 'B014EKQ5AA's daily sales rank hitorical data. I am trying above code and the result is blank. can anyone help me? thanks.

**Comment by akaszynski** [comment]
Could you please create a new issue and post the code you used as well?

**Comment by shashankdogra** [comment]
I've used the stats array inside of product object to get the sales rank data. 


products = api.query(asins, offers=20, stats=90, history=0, rating=1)
stats = product['stats']
currentRank = stats['current'][3]
average30Rank = stats['avg30'][3]
average90Rank = stats['avg90'][3]
average180Rank = stats['avg180'][3]

this is normal output that I'm using to get into a csv, not a plot. Hope it helps

**Comment by maplejia** [comment]
thanks! I will
    On Friday, August 23, 2019, 12:37:15 PM CDT, Alex Kaszynski <notifications@github.com> wrote:  
 
 
Could you please create a new issue and post the code you used as well?
