### ISSUE TITLE
Problem at api = keepa.Api(accesskey)

### ISSUE THREAD

**Issue by Anthon02** [akaszynski/keepa#41]
Hi,

Thanks for making the software available. Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32
Windows 10 32bit
on a HyperV virtual machine

Same error on my Windows 10 64bit machine

I install the module using “pip install keepa”
Running this code in sublime3:
```
import keepa
accesskey = ‘6999999999999999999999999’
api = keepa.Keepa(accesskey)
products = api.query(‘B0088PUEPK’) # returns list of product data #B07D3DTW4G
```

I get: AttributeError: module ‘keepa’ has no attribute ‘Keepa’

i also tried the same code with the following in place of api = keepa.Keepa(accesskey)

`api = keepa.Api(accesskey)`

Same error.

Any help would be appreciated.

Thanks

**Comment by akaszynski** [comment]
What version of `keepa` are you using?

**Comment by Anthon02** [comment]
I just downloaded the module yesterday. Version 0, 18, 0

**Comment by akaszynski** [comment]
Can you run the following?
```python
from keepa.interface import Keepa
```

**Comment by Anthon02** [comment]
I get

ModuleNotFoundError: No module named 'keepa.interface'; 'keepa' is not a package

**Comment by Anthon02** [comment]
Is there an earlier version I could use in the meantime?

**Comment by akaszynski** [comment]
I can't reproduce this locally.  I recommend you try cloning this repo and installing from the source.  There's likely a problem with your install.  When you install it, use the ``-e`` development flag.

**Comment by Anthon02** [comment]
Cloning repo? Do you mean renaming the package directory?

**Comment by akaszynski** [comment]
You can either click the download button on the main page of this git website, or run:
```bash
$ git clone https://github.com/akaszynski/keepa
$ cd keepa
$ pip install -e .
```
Looks like you're using windows.  You can get Git for Windows at https://git-scm.com/download/win

**Comment by Anthon02** [comment]
I ran pip install -e and got this.



>PS C:\Windows\system32\keepa> pip install -e
> 
> Usage:
>   pip install [options] <requirement specifier> [package-index-options] ...
>   pip install [options] -r <requirements file> [package-index-options] ...
>   pip install [options] [-e] <vcs project url> ...
>   pip install [options] [-e] <local project path> ...
>   pip install [options] <archive url/path> ...
> 
> -e option requires 1 argument

**Comment by akaszynski** [comment]
Looks like you forgot the period.
```
pip install -e .
```

**Comment by Anthon02** [comment]
Got it. It worked. What do I do next?

**Comment by akaszynski** [comment]
Do you encounter the same problem when importing ``keepa``?

**Comment by Anthon02** [comment]
Yes. 

AttributeError: module 'keepa' has no attribute 'Keepa'

**Comment by Anthon02** [comment]
It not when I import keepa. The error occurs at 

`api = keepa.Keepa(accesskey)`

**Comment by akaszynski** [comment]
Please run this and let me know what it outputs.
```python
import keepa
print(keepa.__file__)
```

**Comment by Anthon02** [comment]
C:\inetpub\wwwroot\keepa.py

**Comment by Anthon02** [comment]
That is the location and name of the script I running.

**Comment by Anthon02** [comment]
I change the name of my script and now it works.

**Comment by akaszynski** [comment]
Glad we figured it out.

**Comment by Anthon02** [comment]
Can I ask a question here?

**Comment by akaszynski** [comment]
Please email me at akacap@gmail.com

**Comment by Anthon02** [comment]
I figured it out. Thanks for your help.
Anthony Brea  





On Thu, Jul 25, 2019 8:26 AM, Alex Kaszynski notifications@github.com  wrote:
Please email me at akacap@gmail.com
