### ISSUE TITLE
historical daily sales rank data

### ISSUE THREAD

**Issue by maplejia** [akaszynski/keepa#42]
Hi, all,
I have purchase keepa api and got its key. But I am new to python and still don't know how to get daily sales rank data per Asin?

here is my code: 

import keepa
import logging
import inspect
logging.basicConfig()
import datetime
import requests
import numpy as np
accesskey = 'xxxxx'
api = keepa.Keepa(accesskey)
asins = 'B00IIFW2L4'
products = api.query(asins, offers=20, stats=90, history=0, rating=1) # I think you were missing this
product = products[0]
offers = product['offers']
categoryTree = product['categoryTree']
stats = product['stats']

print('\nASIN is:\n' + products[0]['asin'])
currentPrice = stats['current'][18]
currentRank = stats['current'][3]

print ('Current Price:\t\t\t' + str(currentPrice/100.00))
print ('Current Rank:\t\t\t' + str(currentRank))

here is the output:
ASIN is:
B00IIFW2L4
Current Price:			64.99
Current Rank:			621

But what i want is historical daily sales rank data, like:
Date(daily):                     sales rank                           price USD
10222014                            1                                           70.00
10232014                             3                                          69.00
…                                          …
08252019                            1                                            64.99

Would you please help me on it? thanks

**Comment by akaszynski** [comment]
Please see:
https://keepaapi.readthedocs.io/en/latest/product_query.html#product-history-query
