### ISSUE TITLE
salesrank data error？

### ISSUE THREAD

**Issue by maplejia** [akaszynski/keepa#43]
Dear all,

I am using keepa API to pull out the sales rank data from keepa. one product sales rank seems wrong.
 for example, product( Asin: B00UG9HB1Q) was sold in Amazin since 2018 and the sales rank data start from 2015. 
amazon link: https://www.amazon.com/AmazonBasics-Security-Safe-Cubic-Feet/dp/B00UG9HB1Q/ref=cm_cr_arp_d_product_top?ie=UTF8
my code and output:
![salesrankcode](https://user-images.githubusercontent.com/51168359/63658631-cf9e4a00-c771-11e9-9ce4-c43d0b41e176.JPG)

the sales rank data chart from https://www.profitguru.com/products, which is match with Amazon
![guru](https://user-images.githubusercontent.com/51168359/63658662-0d9b6e00-c772-11e9-8104-46724afa7ec5.png)

anyone can help me on it? thanks.

**Comment by akaszynski** [comment]
The data appears to be quite similar.  Can you plot both of them on the same plot?

**Comment by akaszynski** [comment]
This seems like a non-issue.  Closing soon...
