### ISSUE TITLE
module 'keepa' has no attribute 'Api'

### ISSUE THREAD

**Issue by trainake1** [akaszynski/keepa#44]
Weather it is (module 'keepa' has no attribute 'Api')
or
module ('keepa' has no attribute 'keepa')

I cannot get past the third line of code.

import keepa

accesskey = 'xxxxxxxxxxx'

api = keepa.Api(accesskey)

**Comment by akaszynski** [comment]
Please be sure you don’t have any folders or files also named keepa

**Comment by akaszynski** [comment]
Please run:
```python
import keepa
print(keepa.__file__)
```

**Comment by akaszynski** [comment]
You typed `file`.  Please type `__file__`

**Comment by akaszynski** [comment]
That’s supposed to two underscores.

Are you sure there’s no file or folder named keepa in the path you’re running this script from?  Also, did you install it using pip?

**Comment by akaszynski** [comment]
Looks like it’s installed correctly.  Which version are you running?  See `__version__`.

**Comment by akaszynski** [comment]
Interesting.  It’s correctly installed and is the latest version.  Can you try uninstalling it using pip and then cloning this repo and trying to install it from there.

**Comment by trainake1** [comment]
Can you send me the files directly to save into my folders?
No luck in installing from repo

**Comment by akaszynski** [comment]
Sorry, should have looked more throughly at your code.  Turns out you should be using:
```python
import keepa

key = 'putyourkeyhere'
api = keepa.Keepa(key)
```
