### ISSUE TITLE
brand is one of filtering

### ISSUE THREAD

**Issue by threemonks** [akaszynski/keepa#48]
keepa api filters brand/label/manufacturer/publisher/studio using "is one of", so the value for that filtering is a list, not a str. Seem like the code is casting that list into a string, thus returns no result usually. This is also true for all other text fields searching in keepa api, including but not limited to model, size, etc.

**Comment by akaszynski** [comment]
Could you please provide a code so I can debug it?  I'm unfamiliar with that section of the source.

**Comment by threemonks** [comment]
looking at code 1873 of interface.py, it changes the following product_parms:

{'brand': ['disney', 'disney frozen']}

into:

{'brand': "['disney', 'disney frozen']"}

because of the following code:

for key in product_parms:
            if key not in PRODUCT_REQUEST_KEYS:
                raise RuntimeError(f'Invalid key "{key}"')

            # verify json type
            key_type = PRODUCT_REQUEST_KEYS[key]
            product_parms[key] = key_type(product_parms[key])

and the configuration line 302 in  file product_finder_keys.py:

'brand': str,

It should be:

'brand': list,

And similarly the following parameters should be of type list, instead of str:

type, manufacturer, brand, label, department, publisher, productGroup, studio, genre, model, color, size, edition, platform, format, author, binding, languages, mpn, partNumber

**Comment by akaszynski** [comment]
Thanks for spelling that out.  Code updated as of ``keepa==0.19.2``.
