### ISSUE TITLE
Python 3's f-Strings compatibility issue with python 2

### ISSUE THREAD

**Issue by threemonks** [akaszynski/keepa#49]
It looks like you introduced some python 3 specific f-strings, which make the code no longer works for python 2? In interface.py you have:

`raise RuntimeError(f'Invalid key "{key}"')`

Would it be possible that you keep it backwards compatible with python 2?

Thanks

**Comment by akaszynski** [comment]
I can, but I won’t be able to implement it for a bit as I’m traveling right now.  Could you please submit a pull request?

**Comment by threemonks** [comment]
Submitted a new pull request.

**Comment by akaszynski** [comment]
Thanks for the pull request.  I've merged it and pushed version ``0.19.2`` to PyPi.

I'd recommend switching over to Python 3 soon as support for Python 2.7 will be dropped at the end of 2019.  The switch is generally not too much work, and there's quite a few tools out there that convert Py2.7 source to Py3+.

**Comment by threemonks** [comment]
Thanks. That's on my todo list, but haven't got chance to complete it yet.
