### ISSUE TITLE
Async keepa

### ISSUE THREAD

**Issue by chocobn69** [akaszynski/keepa#51]
Hello,

Few months ago, I had to use keepa in an async loop.
So I forked this project to transform keepa lib into asynckeepa.

I'm wondering how I could merge my work into your project back.

You can check what I did here : https://github.com/alexandriagroup/asynckeepa

It's working very well

**Comment by chocobn69** [comment]
Important part is here : https://github.com/alexandriagroup/asynckeepa/blob/master/asynckeepa/interface.py#L848

**Comment by akaszynski** [comment]
Do you know how to create a pull request on GitHub?  If you’d rather not, i can add the code.

**Comment by chocobn69** [comment]
Yes I do know how to do it. But the problem is it will break every _not async_ code.

We might find a way to have async / not async code. I think Django is using a non async warpper to handle async code in lower level for 3.0 version. It could a way to handle it.

**Comment by akaszynski** [comment]
Why not create two classes.  One asynchronous, one vanilla?

**Comment by chocobn69** [comment]
Yes that's an idea.
Better than mine :)

I have to check how inheritance works with async / await

**Comment by akaszynski** [comment]
There are still those using Python2.7, so the async version must be separate from the non-async version.  Looking at the code, it may not be possible to subclass async, so we're going to have to have both classes exist separately for now.  We can provide support for the original approach until the end of this year (or a little after) and then drop support for the old approach and only support the new one.

What's the speedup using the async method?

**Comment by akaszynski** [comment]
Also, for unit testing and documentation, I need some example code for using the Async module.

**Comment by akaszynski** [comment]
Still interested in contributing code?

**Comment by chocobn69** [comment]
Yes I am, I just need some time to work on it

Le sam. 30 nov. 2019 à 04:08, Alex Kaszynski <notifications@github.com> a
écrit :

**Comment by chocobn69** [comment]
Hi, I did not forget about this.
Here is 3 ways to deal with bot async and not async lib : https://stackoverflow.com/questions/55152952/duplication-of-code-for-synchronous-and-asynchronous-implementations

I think a wrapper should do the job

**Comment by akaszynski** [comment]
Thanks for that!  That looks like the way to go.

Would you mind submitting a PR with the async wrapper?  I'm a bit busy at the moment and you probably have more experience with it.
