### ISSUE TITLE
deals ?

### ISSUE THREAD

**Issue by ilmetu** [akaszynski/keepa#53]
how we can perform a deal request ?

**Comment by akaszynski** [comment]
It's not currently setup, but if you can point to me to either the java source or some documentation from https://keepa.com/, I build it into `keepa`.

**Comment by ilmetu** [comment]
this is the api 👍 
https://keepa.com/#!discuss/t/browsing-deals/338

thanks for your answer

**Comment by akaszynski** [comment]
Took a bit for me to work on this, but I finally added it in 2cd5828dff2ab26226bbb5a4f5f72948ae2aa50f.  I'll have it out in the next release shortly.
