### ISSUE TITLE
How to Install Keepa on Python

### ISSUE THREAD

**Issue by nakazas** [akaszynski/keepa#54]
Dear Keepa Community,

Trust you are well. I would like to ask for your help regarding how to install Keepa on Python. 

I just have subscribed to Keepa to extract historical prices on Amazon; however, I am not sure where to start. Could you please guide me through the process? For your information, I am new to Python and would like to start learning it.

Best regards,
nakazas

**Comment by akaszynski** [comment]
Hello,

Please see the docs at https://keepaapi.readthedocs.io/en/latest/ for installation and usage.

**Comment by nakazas** [comment]
Dear akaszynski,

Thank you very much. I was able to install keepa. 

Best regards,
nakazas
