### ISSUE TITLE
How to Extract Latest 365 days of Amazon Product Price 

### ISSUE THREAD

**Issue by nakazas** [akaszynski/keepa#55]
Dear Alex,

Thank you very much for your helpful guidance to install the module. I was able to follow it. Now, I would like to extract the most recent 365 days for a certain product. I was able to extract the first 10 days or first XX days of price information, but not the most recent ones. Would you be able to help me out with this, please? 

Best regards,
nakazas

**Comment by akaszynski** [comment]
Please post what you've tried out so I can help extend your example.  Be sure not to post your access key.

**Comment by nakazas** [comment]
Dear Alex,

Thank you for your prompt response. I was able to write the code below following your instruction, but I am not sure how to get the most recent 365 days of price information for a certain product.

`>>> products = api.query('B018COT3VW')
>>> product = products[0]
>>> newprice = product['data']['NEW']
>>> newpricetime = product['data']['NEW_time']
>>> print('%20s %s' % ('Date', 'Price'))
                Date Price
>>> for i in range(10):
...    print('%20s   $%.2f'   %   (newpricetime[i], newprice[i]))
...
 2015-12-31 00:41:00   $10.00
 2016-01-02 09:57:00   $13.95
 2016-01-25 15:01:00   $nan
 2016-01-28 04:55:00   $15.95
 2016-03-24 08:59:00   $nan
 2016-03-26 21:40:00   $15.95
 2016-04-23 06:05:00   $11.73
 2016-04-29 18:55:00   $15.95
 2016-05-05 08:06:00   $11.73
 2016-05-12 04:36:00   $15.95
>>>      
`
Best regards,
Seiyo Nakazawa

**Comment by nakazas** [comment]
Dear Keepa Community, 

Does anyone know how to extract the most recent 365days worth of information? Or simply, does anyone know how to extract all of pricing information of a certain items? 

Best regards,
nakazas

**Comment by akaszynski** [comment]
Hello,

Sorry for the delayed response.  Here's how you'd get the data for the past year for a product:

```python
from keepa import Keepa
api = Keepa(mykey)
products = api.query('B018COT3VW')
product = products[0]

newprice = product['data']['NEW']
newpricetime = product['data']['NEW_time']


# get datetime a year ago
from datetime import datetime
from dateutil.relativedelta import relativedelta
year_ago = datetime.now() - relativedelta(years=1)

# arrays from the product you're interested in
newprice = product['data']['NEW']
newpricetime = product['data']['NEW_time']

# data for only the past year
time_mask = newpricetime > year_ago
print(newprice[time_mask])
print(newpricetime[time_mask])
```
```
[12.5  15.95 12.5  15.95]
[datetime.datetime(2020, 2, 21, 18, 4)
 datetime.datetime(2020, 2, 22, 10, 20)
 datetime.datetime(2020, 2, 27, 20, 28)
 datetime.datetime(2020, 2, 29, 22, 30)]
```
