### ISSUE TITLE
Print estimated time remaining

### ISSUE THREAD

**Issue by volcompt** [akaszynski/keepa#56]
This is not exactly an issue. It's probably me who don't know how the logging feature works. 
I was reading the code and it apparently stores the estimated time for completion of a request. Is there anyway I can print that to the screen when making a multiple product query?

**Comment by akaszynski** [comment]
It's probably better to use `tqdm` to give a better estimate for a multiple item query.  Let me see how hard that's to implement.

**Comment by akaszynski** [comment]
Fixed in #57.  Install release `keepa==0.19.3` to get the time indicator with the progress bar.

**Comment by volcompt** [comment]
Thanks. That was super quick. Will test!
