### ISSUE TITLE
Buybox filter in product request

### ISSUE THREAD

**Issue by germangtzg** [akaszynski/keepa#59]
Hi, 

Keepa recently added a buybox parameter for product requests, as shown below. Would it be possible to add it to the code? 

✜ buybox
Additional token cost: 2 per product
Boolean value (0 = false, 1 = true). If specified and has the value 1 the product and statistics object will include all available buy box related data:

Thanks a lot!

**Comment by akaszynski** [comment]
Could you please point me to the buy box documentation on keepa?

**Comment by germangtzg** [comment]
Sure, see the last option in the following link:
https://keepa.com/#!discuss/t/request-products/110

Thanks a lot!

**Comment by akaszynski** [comment]
This feature will be out in `0.20.1` on https://pypi.org/project/keepa/ shortly.

**Comment by germangtzg** [comment]
thanks a lot!
