### ISSUE TITLE
Not able to use keepa.Keepa(accesskey) in Google Colab

### ISSUE THREAD

**Issue by neoskywalker7** [akaszynski/keepa#65]
Hi I am trying to call api = keepa.Keepa(accesskey) on Colab. Not sure why it returns This event loop is already running error. I am pretty sure I only maintain one session. Does anyone know what’s the issue? Tried generating new accessKey, but it is still not working.

Thanks

**Comment by akaszynski** [comment]
Is it due to the new async interface?  Try using an older version of `keepa` (e.g. `keepa==0.20.1`)

**Comment by neoskywalker7** [comment]
Thanks, it works!

**Comment by akaszynski** [comment]
Reopening as this is something I have to look into.

**Comment by Rizwana96** [comment]
I'm still getting the same error on jupyter even after installing the other version keepa==0.20.1? @akaszynski

**Comment by chocobn69** [comment]
Older version should not get you any This event loop is already running error.

**Comment by chocobn69** [comment]
If you have access to async loop, you may be able to use keepa the async way :

**Comment by Rizwana96** [comment]
I installed ayncio library and it works.

**Comment by Olaf011** [comment]
I can't access with `api = await keepa.AsyncKeepa.create(accesskey)`.
![image](https://user-images.githubusercontent.com/52181901/103468591-0e2b1800-4d5b-11eb-867c-7c40a51c0b13.png)

**Comment by Katgitmake** [comment]
![image](https://user-images.githubusercontent.com/81460680/112712850-5e240180-8ea8-11eb-922f-e1f7bca658df.png)
