### ISSUE TITLE
New fields for products in Java api_backend

### ISSUE THREAD

**Issue by yousuowei123** [akaszynski/keepa#66]
*/
	public FBAFeesObject fbaFees = null;

	/**
	 * Contains subcategory rank histories. Each key represents the categoryId of the rank with the history in the corresponding value.
	 */
	public HashMap<Long, int[]> salesRanks = null;

	/**
	 * The category node id of the main sales rank. -1 if not available.
	 */
	public long salesRankReference = -1;

**Comment by akaszynski** [comment]
Addressing this (finally) in #128 by adding a reference to the backend documentation. In this case, I think linking will work better.
