### ISSUE TITLE
Please add range parameter for best_sellers_query

### ISSUE THREAD

**Issue by LeSonicDev** [akaszynski/keepa#69]
The range parameter is explained at https://keepa.com/#!discuss/t/request-best-sellers/1298

Please update code to support range parameter. Thanks.

**Comment by LeSonicDev** [comment]
I can do the update if it's OK with you. For now I am creating a class inherits AsyncKeepa and add new method supporting range parameter.

**Comment by akaszynski** [comment]
Feel free to submit a PR and I'll be sure to review it.

**Comment by LeSonicDev** [comment]
Hi Akaszynski,

I don't have permission to push my new created local branch 'add-query-parameters' to keepa repo hosted on github. Can I submit a PR without this permission?

**Comment by akaszynski** [comment]
Yes, but you’ll have to fork the repository first and then submit a PR.

Thanks in advance for working on this!
