### ISSUE TITLE
Why don't merge the paired ndarrays into a DataFrame?

### ISSUE THREAD

**Issue by LeSonicDev** [akaszynski/keepa#70]
I am writing code like this:

import keepa
import pandas as pd

asin = 'B07CMQLJJW'
asin_details = await keepa_api.api.query(asin, stats=30, rating=True)
asin_data = asin_details[0]['data']
sales_rank_of_root_category = pd.DataFrame({'time': asin_data['SALES_time'], 'rank': asin_data['SALES']})

Is there a reason to not merge these paired ndarrays (for example, SALES_time and SALES) into DataFrame in keepa function parse_csv?

**Comment by LeSonicDev** [comment]
Here is how I modify my local copy of keepa:

![image](https://user-images.githubusercontent.com/50606343/94327088-5360e080-ffdb-11ea-8930-5c118897d628.png)

**Comment by akaszynski** [comment]
We could totally add that, and `pandas` Would be an ideal module to organize this data.

At the moment I’m swamped with work, so it’s not ideal time for me to add this in.  If you’re interested, please submit a PR and I’ll review it.
