### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by jeffreylm** [akaszynski/keepa#77]
Dear Everyone,

I have installed the keepa module with: pip install keepa
But now when I try to import and rum keepa, I get the following.

import keepa
ModuleNotFoundError: No module named 'keepa'

Does anyone know how to fix this issue?

Thank you in advance.

**Comment by akaszynski** [comment]
You might have a directory or python file named “keepa” in your path.  You might also be using a different python than your pip (e.g. your pip is for python2.7 and your python env is python3.6)

**Comment by jeffreylm** [comment]
I am running only Python 3.8.
Could you explain what you mean with : You might have a directory or python file named “keepa” in your path.

Sidenote, I'm on a mac. I am an intermediate / beginner (3 months) in python.
