### ISSUE TITLE
Certificate not valid 

### ISSUE THREAD

**Issue by jeffreylm** [akaszynski/keepa#78]
Dear Everyone,

I now have an issue with certificate validation. Can someone make sense of what is going wrong here:

File "/Users/noimportant/opt/anaconda3/envs/product/lib/python3.8/site-packages/aiohttp/connector.py", line 948, in _wrap_create_connection
    raise ClientConnectorCertificateError(
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.keepa.com:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '49.12.156.198'. (_ssl.c:1123)"

I also contacted keepa support about the above issue and there response was that there are no issues on there end with the ssl, and provided a url verifying this: https://www.ssllabs.com/ssltest/analyze.html?d=api.keepa.com&s=49.12.156.204

Thank you in advance

**Comment by heidikmkv** [comment]
I have been having the same issue for several days.

**Comment by akaszynski** [comment]
I'm considering refactoring the `async` features so you can choose to use `async` or not since there are a ton of issues using this on colab.

**Comment by jeffreylm** [comment]
> I have been having the same issue for several days.
> 
> To fix the problem, I downgraded to version 0.20.1 and communication now works, although the asynchronous features aren't there. https://github.com/akaszynski/keepa/releases

Thank you for clearing that up.

**Comment by jeffreylm** [comment]
> I'm considering refactoring the `async` features so you can choose to use `async` or not since there are a ton of issues using this on colab.



> I have been having the same issue for several days.
> 
> To fix the problem, I downgraded to version 0.20.1 and communication now works, although the asynchronous features aren't there. https://github.com/akaszynski/keepa/releases

Did 1.0.0 also not work? I was / am using 1.1.0

**Comment by jeffreylm** [comment]
> I'm considering refactoring the `async` features so you can choose to use `async` or not since there are a ton of issues using this on colab.

Would 1.0.0 work?

Thank you for responding.

**Comment by chocobn69** [comment]
Maybe you should fix your hosting server, has asyncio is using SSL stack provided by OS

**Comment by akaszynski** [comment]
@chocobn69, are you referring to google colab?  If so, that's not something that can be fixed, and means that we need to provide the user with an alternative way of accessing keepa that doesn't make assumptions on the external libraries.  The `requests` approach works quite well.

**Comment by chocobn69** [comment]
I was not referring google colab. @jeffreylm are you using colab ? Can you provide us a test sample so we can reproduce the error ?

**Comment by chocobn69** [comment]
https://github.com/aio-libs/aiohttp/issues/2822
