### ISSUE TITLE
api.deals() does not return ASINs.

### ISSUE THREAD

**Issue by ethankershner** [akaszynski/keepa#81]
Thank you for creating this package! 

When I first create a connection to the API and then use api.deals(), inputting the deals parameter, the output should be a list of (up to 150) ASINs. However, it seems that my results are not actual ASINs, for example:

"B00U20FN1Y"

Additionally, only 49 of these values are returned at a time, not 150. I was wondering if this value needs to be converted somehow or if it is a bug.

**Comment by ethankershner** [comment]
I think I have the answer; in your code you attempt to retrieve an "asinlist" but what the "deals" request actually returns is a list of deal objects, and what I think these values are memory references to these objects which are not parsed by the code.

https://keepa.com/#!discuss/t/deal-object/412

**Comment by Olaf011** [comment]
Did you find a solution for this problem? @ethankershner

**Comment by ethankershner** [comment]
> Did you find a solution for this problem? @ethankershner

No, I ended up actually manually accessing the API using Requests for my application. If you're stuck with the same problem I would suggest doing the same.
