### ISSUE TITLE
Product stats don't work anymore

### ISSUE THREAD

**Issue by p-vbordei** [akaszynski/keepa#93]
After the new stats update, the stats calculations for ASINs don't work anymore.

asin_to_ask_keepa = np.asarray(list(set(df_output.ASIN.head(1))))  # This is just a ASIN in a string
products= api.query(asin_to_ask_keepa, offers = 20,  domain='US', stats = 180)

  0%|          | 0/1 [00:00<?, ?it/s]

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-60-0bad68e32074> in <module>()
      asin_to_ask_keepa = np.asarray(list(set(df_output.ASIN.head(1))))
----> products= api.query(asin_to_ask_keepa, offers = 20,  domain='US', stats = 180)

8 frames

/usr/local/lib/python3.7/dist-packages/keepa/interface.py in normalize_value(v)
     92 
     93                     def normalize_value(v):
---> 94                         if v < 0:
     95                             return None
     96 

TypeError: '<' not supported between instances of 'str' and 'int'

**Comment by kevincojean** [comment]
Thank you for writing this, I have the same issue, I will submit a pull request as soon as I fix this.

**Comment by kevincojean** [comment]
Pull request has been submitted, check the code to get the desired hotfix:
https://github.com/akaszynski/keepa/pull/94

**Comment by kevincojean** [comment]
Fixed

**Comment by akaszynski** [comment]
Thanks @kevincojean for the PR.  1.2.1 is out on PyPi.
