### ISSUE TITLE
Missing product query options

### ISSUE THREAD

**Issue by spi-jbu** [akaszynski/keepa#95]
The 'days' and 'only-live-offers' options for a product query are not implemented in the library.

Thanks

**Comment by kevincojean** [comment]
I don't see those parameters in the Keepa Product Search documentation, could you specify by linking documentation?
[](https://keepa.com/#!discuss/t/product-searches/109)

**Comment by spi-jbu** [comment]
They are in the Product Request page at:

[[https://keepa.com/#!discuss/t/request-products/110]](url)

**Comment by kevincojean** [comment]
I have opened a pull request for this feature implementation:
https://github.com/akaszynski/keepa/pull/96

I have not been able to implement 'days' parameter... as I discuss over there.
If we could redirect discussions over there that would be great!

**Comment by kevincojean** [comment]
I closed my previous PR by mistake, but my implementation was not working.
However I believe I got everything to work (tests are passing) in this PR:
https://github.com/akaszynski/keepa/pull/98

**Comment by akaszynski** [comment]
Closing as this is old and (appears?) resolved.

Reopen if needed.
