### ISSUE TITLE
Error on "api = keepa.Keepa(accesskey)" --> "This event loop is already running"

### ISSUE THREAD

**Issue by dannyavila-loreal** [akaszynski/keepa#97]
When I try to connect, I run into a Runtime Error "This event loop is already running", which appears to be in reference to the line "api = keepa.Keepa(accesskey). I added snippet with fake key.

![image](https://user-images.githubusercontent.com/71674043/112246799-9a95fa00-8c29-11eb-8be9-fdc0deafa310.png)

Thank you,
Danny

**Comment by akaszynski** [comment]
Could you please checkout #65 as it's a similar issue.

**Comment by Katgitmake** [comment]
I am having same issue. #65 response left me with error: SyntaxError: 'await' outside function

**Comment by akaszynski** [comment]
Should be resolved in ``keepa==1.3.0``.  Upgrade to the latest release with `pip install keepa -U`.

**Comment by Katgitmake** [comment]
Worked! Thank you
